server:
    port:   13000

ewus:
    auth:
        url:    https://ewus.nfz.gov.pl/ws-broker-server-ewus-auth-test/services/Auth
    broker:
        url:    https://ewus.nfz.gov.pl/ws-broker-server-ewus-auth-test/services/ServiceBroker

    credentials:
        ow:         01
        user-type:  SWD
        identyfikator-swiadczeniodawcy: 123456789
        login:      TEST
        password:   qwerty!@#

    client:
        name:       client-eWUS
        version:    1.0.0

    persistence:
        execute:    true
        folder:     e:/programowanie/nzoz/stat/

database:
    driver: com.googlecode.paradox.Driver
    url:    jdbc:paradox:e:/programowanie/nzoz/db

job:
    checkCWUForAll:
        cron:   0 30 0 1,2,28,29,30,31 * *
        only-start-and-end-of-the-month:    true